env = SConscript('godot-cpp/SConstruct')

env.Append(CPPPATH='src/')

# env.Append(LIB='...')
# env.Append(LIBPATH='...')

src = Glob("src/*.cpp")

if env['platform'] == 'linux':
    pass
elif env['platform'] == 'windows':
    env.Append(CPPPATH=["src/vcpkg/packages/jsoncpp_x64-windows/include"])
    env.Append(LIBPATH=['src/vcpkg/packages/jsoncpp_x64-windows/debug/lib'])
    env.Append(LIBS=['jsoncpp'])

    libpath = '../libHashtable{}{}'.format( env['suffix'], env['SHLIBSUFFIX'])
    sharedlib = env.SharedLibrary(libpath, src)
    Default(sharedlib)

else:
    pass